### ISSUE TITLE
Feedback for “Solana Swap and Data API by Solana Tracker”

### ISSUE THREAD

**Issue by SixiangLi** [YZYLAB/solana-swap#11]
Why some of the PNL data are missing? Is there any limitation to trace the PNL?
I am referring the following 2 APIs
[GET /pnl/{wallet}](https://docs.solanatracker.io/public-data-api/docs#get-pnlwallet)
[GET /pnl/{wallet}/{token}](https://docs.solanatracker.io/public-data-api/docs#get-pnlwallettoken)

**Comment by YZYLAB** [comment]
This github repo is not for the Data API. It’s better to ask in the
Discord. PNL data is available for the past 2 months currently.

Op za 16 nov 2024 om 16:50 schreef SixiangLi ***@***.***>
