### ISSUE TITLE
No commitment attribute for the function perform swap

### ISSUE THREAD

**Issue by AnthonyRamses** [YZYLAB/solana-swap#3]
On the function perform swap there is no commitment attribute

![image](https://github.com/YZYLAB/solana-swap/assets/82960132/40f25cbc-d373-4ab7-8c92-ec70fa02b77d)

**Comment by YZYLAB** [comment]
In the latest version there is.  Can you confirm you are on the latest version?

**Comment by AnthonyRamses** [comment]
I installed the dependency by using yarn add solana-swap. Not sure if it is the latest version

**Comment by YZYLAB** [comment]
Try: `yarn add solana-swap@latest`

**Comment by AnthonyRamses** [comment]
I tried yarn add solana-swap@latest

This is the current version I have "solana-swap": "^1.0.14"

Still the same issue

![image](https://github.com/YZYLAB/solana-swap/assets/82960132/6e5a76de-39d8-4e9e-98f4-bcc9100532e3)

**Comment by AnthonyRamses** [comment]
Still no luck figuring out how to send the commitment level. Do you recommend to use the API instead?

**Comment by YZYLAB** [comment]
I will take a look tomorrow and push a fix!

**Comment by AnthonyRamses** [comment]
Thanks! Looking forward to continue using the package

**Comment by YZYLAB** [comment]
I believe it should be fixed now if you install version 1.0.15. Please check and let me know

**Comment by AnthonyRamses** [comment]
Yes it's working great now. Thank you very much
