### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by banlieu451** [YZYLAB/solana-swap#6]
Impossible to run your code please we need help : 

When run :  `node example.Ts`
It return :   `import { Keypair } from "@solana/web3.js"; SyntaxError: Cannot use import statement outside a module`

We had in package.json : `"type": "module",`
It return : `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".Ts"`

Sincerely

**Comment by YZYLAB** [comment]
You have your file extensions set to .Ts while it should be .ts since .Ts is not valid typescript.
