### ISSUE TITLE
Why is the amount of sol purchased transferred to this address?

### ISSUE THREAD

**Issue by lonely1215225** [YZYLAB/solana-swap#7]
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/b6c6f2b3-9fdf-4852-8904-42ab762296c3">
<img width="998" alt="image" src="https://github.com/user-attachments/assets/9a80fdd6-404f-4c5e-8b0b-1f1565b2afe5">

**Comment by YZYLAB** [comment]
The swap api charges a fee but that wallet isn't from solana tracker. Are you generating transactions using https://swap-v2.solanatracker.io or this swap library?

**Comment by lonely1215225** [comment]
> The swap api charges a fee but that wallet isn't from solana tracker. Are you generating transactions using https://swap-v2.solanatracker.io or this swap library?swap api 收取费用，但该钱包不是来自 solana tracker。您是否使用 https://swap-v2.solanatracker.io 或此交换库生成交易？

![image](https://github.com/user-attachments/assets/3ddc5652-a6ef-4b9c-ae9c-00febd9c564b)

i use npm install solana-swap
