### ISSUE TITLE
Cant Swap newly created pairs

### ISSUE THREAD

**Issue by sanjulaonline** [YZYLAB/solana-swap#8]
When i'm going to perform a swap in newly launched token, this error will appear from the api

"`Error response from swap API: {'error': 'ApiError', 'errorCode': 'COULD_NOT_FIND_ANY_ROUTE', 'message': 'COULD NOT FIND ANY ROUTE', 'statusCode': 400}`"

**Comment by YZYLAB** [comment]
Hi Sanjula,

That is not an error from the swap api. Are you sure you are using my api?


Op za 5 okt 2024 om 13:35 schreef Sanjula Herath ***@***.***>
